<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-35HBDVU" failures="1" tests="1" name="Default test(failed)" time="0.025" errors="0" timestamp="30 Mar 2025 06:58:34 GMT">
  <testcase classname="com.app.test.Validation_One" name="test1" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [Aiit] but found [Aiite]">
      <![CDATA[java.lang.AssertionError: expected [Aiit] but found [Aiite]
	at com.app.test.Validation_One.test1(Validation_One.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="com.app.test.Validation_One" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="com.app.test.Validation_One" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Default test(failed) -->
